import { writeFile, mkdir, access } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

export interface InitOptions {
  url?: string;
  target?: string;
  command?: 'check' | 'scan';
  force?: boolean;
}

const DEFAULT_TARGET = '.github/workflows/schemaguardian.yml';

export async function runInit(opts: InitOptions): Promise<number> {
  const target = opts.target ?? DEFAULT_TARGET;
  const command = opts.command ?? 'scan';
  const url = opts.url ?? 'https://your-site.com';

  const absPath = resolve(process.cwd(), target);

  if (!opts.force) {
    try {
      await access(absPath);
      process.stderr.write(
        `schemaguardian: ${target} already exists. Re-run with --force to overwrite.\n`,
      );
      return 1;
    } catch {
      // doesn't exist — proceed
    }
  }

  const content = renderWorkflow({ url, command });

  try {
    await mkdir(dirname(absPath), { recursive: true });
    await writeFile(absPath, content, 'utf8');
  } catch (e) {
    process.stderr.write(
      `schemaguardian: failed to write ${target}: ${e instanceof Error ? e.message : String(e)}\n`,
    );
    return 1;
  }

  process.stdout.write(`✓ wrote ${target}\n`);
  process.stdout.write('\n');
  process.stdout.write('Next steps:\n');
  process.stdout.write(`  1. Edit ${target} and replace https://your-site.com with your URL.\n`);
  process.stdout.write('     (Skip if you used --url.)\n');
  process.stdout.write('  2. Commit + push. The workflow runs on every PR and push to main.\n');
  if (command === 'scan') {
    process.stdout.write('  3. The default uses `scan` to walk your sitemap.xml. If you do not\n');
    process.stdout.write('     have a sitemap, swap to `check <url>` for single-page validation.\n');
  } else {
    process.stdout.write('  3. The default uses `check` for single-page validation. If you have\n');
    process.stdout.write('     a sitemap.xml, swap to `scan` to walk every URL.\n');
  }
  process.stdout.write('\n');
  process.stdout.write('Read more: https://faqjsonld.com/cli\n');
  return 0;
}

function renderWorkflow({ url, command }: { url: string; command: 'check' | 'scan' }): string {
  const cmd =
    command === 'scan'
      ? `npx --yes @moonye/schemaguardian@latest scan ${url} --ci`
      : `npx --yes @moonye/schemaguardian@latest check ${url} --ci`;

  return `name: schemaguardian
# Validates JSON-LD structured data on ${url}
# Generated by \`npx @moonye/schemaguardian init\`
# Docs: https://faqjsonld.com/cli

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  schema-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Schema ${command}
        run: ${cmd}
`;
}
